;/*FB_PKG_DELIM*/

__d("FDSAirplaneFilled20Icon",["cr:14276"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14276")}),98);
__d("FDSAirplaneFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("571771"),20);b=a;g["default"]=b}),98);
__d("FDSPostSlashFilled20Icon",["cr:13848"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:13848")}),98);
__d("FDSPostSlashFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("1501526"),20);b=a;g["default"]=b}),98);
__d("FDSShieldFilled20Icon",["cr:14248"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14248")}),98);
__d("FDSShieldFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("492714"),20);b=a;g["default"]=b}),98);
__d("FDSUndoFilled16Icon",["cr:15840"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15840")}),98);
__d("FDSUndoFilled16PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("685851"),16);b=a;g["default"]=b}),98);
__d("FDSWatchTvFilled20Icon",["cr:15866"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15866")}),98);
__d("FDSWatchTvFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("607169"),20);b=a;g["default"]=b}),98);
__d("XCometCommunityThreadsControllerRouteBuilder",["jsExtraRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsExtraRouteBuilder")("/messages/c/{folder_id}/t/{thread_key}/",Object.freeze({}),["/messages/c/{folder_id}/"],void 0);b=a;g["default"]=b}),98);
__d("XMessengerDotComCometCommunityThreadsControllerRouteBuilder",["jsExtraRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsExtraRouteBuilder")("/c/{folder_id}/t/{thread_key}/",Object.freeze({}),["/c/{folder_id}/"],void 0);b=a;g["default"]=b}),98);
__d("MWInboxCommunityThreadsRouteBuilder",["CurrentEnvironment","XCometCommunityThreadsControllerRouteBuilder","XMessengerDotComCometCommunityThreadsControllerRouteBuilder"],(function(a,b,c,d,e,f,g){"use strict";a=c("CurrentEnvironment").facebookdotcom?{buildUriForMessage:function(a){var b=a.folder_id;a=a.thread_key;return c("XCometCommunityThreadsControllerRouteBuilder").buildUri({folder_id:b,thread_key:a})},buildURL:function(a){var b=a.folder_id;a=a.thread_key;return c("XCometCommunityThreadsControllerRouteBuilder").buildURL({folder_id:b,thread_key:a})},buildURLWithoutThread:function(a){a=a.folder_id;return c("XCometCommunityThreadsControllerRouteBuilder").buildExtraURL("/messages/c/{folder_id}/",{folder_id:a})}}:{buildUriForMessage:function(a){var b=a.folder_id;a=a.thread_key;return c("XMessengerDotComCometCommunityThreadsControllerRouteBuilder").buildUri({folder_id:b,thread_key:a})},buildURL:function(a){var b=a.folder_id;a=a.thread_key;return c("XMessengerDotComCometCommunityThreadsControllerRouteBuilder").buildURL({folder_id:b,thread_key:a})},buildURLWithoutThread:function(a){a=a.folder_id;return c("XMessengerDotComCometCommunityThreadsControllerRouteBuilder").buildExtraURL("/c/{folder_id}/",{folder_id:a})}};b=a.buildURL;d=a.buildURLWithoutThread;g.buildURL=b;g.buildURLWithoutThread=d}),98);
__d("MWLSGroupMembershipDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9265370860258042"}),null);
__d("MessengerDefaultTheme",["CurrentEnvironment","I64"],(function(a,b,c,d,e,f,g){"use strict";var h;a={color:c("CurrentEnvironment").messengerdotcom?"#0099FF":"#0084FF",id:(h||(h=d("I64"))).of_string("196241301102133"),label:"Default Blue",type:"solid"};g["default"]=a}),98);
__d("VideoPlayerHTML5ApiWebVttState",["Bootloader","unrecoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";a=function(){function a(a){var b=this,d=a.onReady,e=a.onCaptionsLoaded,f=a.captionsDisplay;this.$1=null;this.source=null;this.captionsDisplay=null;this.$1=c("Bootloader").loadModules(["VideoPlayerWebVttCaptionsSource"],function(a){a=new a({onCaptionsLoaded:e,onCaptionsChanged:function(a,c){b.captionsDisplay&&b.captionsDisplay.handleCaptionsChanged(a,c)}});b.source=a;b.captionsDisplay=f;d(b)},"VideoPlayerHTML5ApiWebVttState")}var b=a.prototype;b.loadFromUrl=function(a){var b=this.source;if(!b)throw c("unrecoverableViolation")("[VideoPlayerHTML5ApiWebVttState] Called loadFromUrl when not ready; call from onReady callback.","video_captions");b.loadFromUrl(a)};b.getCurrentScreenRepresentation=function(){return this.source?this.source.getCurrentScreenRepresentation():null};b.destroy=function(){this.$1&&(this.$1.remove(),this.$1=null),this.captionsDisplay&&(this.captionsDisplay.destroy(),this.captionsDisplay=null),this.source&&(this.source.destroy(),this.source=null)};return a}();g["default"]=a}),98);
__d("XGroupsC4GThreadViewControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/groups/{idorvanity}/chats/{thread_id}/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("useJSON",["react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h;(h||d("react")).useMemo;function a(a,b){var c=d("react-compiler-runtime").c(3),e;c[0]!==b||c[1]!==a?(e=JSON.parse(a,b),c[0]=b,c[1]=a,c[2]=e):e=c[2];b=e;return b}g["default"]=a}),98);